AllRecipe/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^oauth/', include('social_django.urls', namespace='social')), 
    url(r'',include("Userapp.urls")),
    url(r'',include("Adminapp.urls")),
   
]

Userapp/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Userapp.views import Login,Home,Register,UserPage,ViewProfile,AdminView,EditProfile,Feedbackv,ViewFeedback

urlpatterns=[
	url(r'^login/',Login.as_view(),name='login'),
	url(r'^logout/',auth_views.logout,name='logout'),
	url(r'^home/',Home.as_view(),name='home'),
	url(r'^register/',Register.as_view(),name='register'),
	url(r'^userpage/',UserPage.as_view(),name='userpage'),
	url(r'^profile/',ViewProfile.as_view(),name='Profile'),
	url(r'^editprofile/',EditProfile.as_view(),name='editprofile'),
	url(r'^adminpage/',AdminView.as_view(),name='adminpage'),
	url(r'^feedback/',Feedbackv.as_view(),name='feedback'),
	url(r'^viewfeedback/',ViewFeedback.as_view(),name='viewfeedback'),
	
	url('^', include('django.contrib.auth.urls')),

]

#urlpatterns += staticfiles_urlpatterns 

Adminapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Category(models.Model):
	category_name=models.CharField(max_length=255)
	category_pic=models.ImageField(upload_to="profilepic")
	def __str__(self):
		return self.category_name
class SubCategory(models.Model):
	category_name=models.ForeignKey(Category,on_delete=models.CASCADE)	
	subcategory_name=models.CharField(max_length=255)
	subcategory_pic=models.ImageField(upload_to="profilepic")
	def __str__(self):
		return self.subcategory_name
class Recipe(models.Model):
	category_name=models.ForeignKey(Category)
	subcategory_name=models.ForeignKey(SubCategory)
	recipe_name=models.CharField(max_length=255)
	recipe_pic=models.ImageField(upload_to="profilepic")
	ingrediants=models.TextField(max_length=2000)
	instructions=models.TextField(max_length=2000)
	price=models.IntegerField()
	approved=models.BooleanField(default=False)
	def __str__(self):
		return self.recipe_name


	

Userapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Feedback(models.Model):
	user_data=models.ForeignKey(User)
	how_you_rate_the_website_overall=models.CharField(max_length=50,choices=(("excellent","excellent"),("good","good"),("satisfactory","satisfactory")),default="excellent")
	suggestions=models.TextField(max_length=2000)
	

Userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UserChangeForm
from Userapp.models import Feedback


class RegisterForm(UserCreationForm):
	class Meta:
		model=User
		fields=['username','email','password1','password2']
class EditUserForm(UserChangeForm):
	UserChangeForm.password = None
	class Meta:
		model=User
		fields=['username','email']

class FeedbackForm(forms.ModelForm):
	class Meta:
		model=Feedback
		fields=['user_data','how_you_rate_the_website_overall','suggestions']
		how_you_rate_the_website_overall=forms.ChoiceField(label="",initial='',widget=forms.Select(),required=True)
	

Userapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect

from django.views.generic import View,TemplateView,CreateView,UpdateView,ListView
from django.contrib.auth.forms import AuthenticationForm
from Userapp.forms import RegisterForm,EditUserForm,FeedbackForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from Userapp.models import Feedback
from django.conf import settings
import urllib
import urllib2
import json



from django.core.mail import send_mail

# Create your views here.

class Login(View):
	def get(self,request):
		form=AuthenticationForm()
		context={'form':form}
		if not request.user.is_authenticated:
			return render(request,'login.html',context)
		else:
			return redirect('home')
	def post(self,request):
		a=request.POST.get('username')
		b=request.POST.get('password')
		user=authenticate(username=a,password=b)
		
		''' 
		recaptcha_response = request.POST.get('g-recaptcha-response')
		url = 'https://www.google.com/recaptcha/api/siteverify'
		values = {
		'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
		'response': recaptcha_response
		    }
		data = urllib.urlencode(values)
		req = urllib2.Request(url, data)
		response = urllib2.urlopen(req)
		result = json.load(response)
		 '''
		if user:# and result['success']:
			login(request,user)
			if request.user.is_superuser:
				return redirect('adminpage')
			else:
				return redirect('home')
		else:
			form=AuthenticationForm
			context={'form':form}
			return render(request,'login.html',context)
	
class Home(TemplateView):
	template_name='home.html'
	
class Register(CreateView):
	form_class=RegisterForm
	template_name='register.html'
	success_url='/home'
	def post(self,request):
		send_mail('registration','successful','allrecipe@example.com',[request.POST.get('username')+'@example.com'])
		return super(Register,self).get(self,request)

	



class UserPage(TemplateView):
	template_name='userpage.html'
class ViewProfile(TemplateView):
	template_name='profile.html'
	def get(self,request):
		print(request.user)
		return render(request,self.template_name,{'user':request.user})
class AdminView(TemplateView):
	template_name='adminpage.html'
class EditProfile(UpdateView):
	form_class=EditUserForm
	model=User
	template_name='editprofile.html'
	def get_object(self, queryset=None):
		return self.request.user
	def get_success_url(self):
		return '/profile'

class Feedbackv(CreateView):
	form_class=FeedbackForm
	model=Feedback
	template_name='feedback.html'
	success_url='feedback'

class ViewFeedback(TemplateView):
	template_name='viewfeedback.html'
	
	model=Feedback
	def get(self,request):	
		x=Feedback.objects.all()
		print(x)
		return render(request,self.template_name,{'feedback':x})









	

Userapp/templates/addrecipe.html
<!doctype html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style type="text/css">
	body{
		background-color: pink;
	}
</style>

</head>
<body>

<h3 align="center"> Add Recipes </h3> <hr>

  


  <form method="post" enctype="multipart/form-data" id="id1" data-subcategorylist="{% url 'ajaxsubcatlist' %}" novalidate>

	{% csrf_token %}
	<table>
	    	{{ form.as_table }}
	</table>
<button type="submit"> submit </button>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
  //alert("a");
  	$("#id_category_name").change(function() {
  		var url = $("#id1").attr("data-subcategorylist");
  		//alert(url);
  		var category_name =$(this).val();

  		$.ajax({                       
        url: url,                    
        data: {
          'category': category_name      
        },
        success: function (data) {   
	//alert(data);
          $("#id_subcategory_name").html(data);  
        }
      });

    });
</script>
</body>
</html>

Userapp/templates/adminpage.html
<!DOCTYPE html>
<html>
<head>
	<title> </title>
		<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style type="text/css">
		body{
			background-color: pink;
		}
	</style>

</head>
<body>
	
		<h3 align="center"> Welcome Admin </h3> <hr>
		<div class="pagination">
			<a href="{% url 'addcat' %}">Add category </a>&nbsp;

			<a href="{% url 'addsubcat' %}"> Add subcategory </a>&nbsp;

			<a href="{% url 'addrecipe' %}">  Add recipe </a> &nbsp;
			<a href="{% url 'viewrecipe' %}"> View recipe </a> &nbsp;
			<a href="{% url 'viewfeedback' %}"> View feedback
		
			<a href="{% url 'logout' %}"> Logout </a>
		</div>
		<form method="post" enctype="multipart/form-data">
	    	{% csrf_token %}
	    	{{ form.as_p }}
	    	<button type="submit"> submit </button>
	  	</form>
	 
</body>
</html>

Userapp/templates/edit recipe.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
	body{
		background-color: pink;
	}
</style>
</head>
<body>

	<form method="post"> 
	{% csrf_token %}
	{{form.as_p}}

	<button type="submit"> update </button>

</form>


</body>
</html>

Userapp/templates/editrecipeus.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
 	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
	body{
		background-color: pink;
	}
</style>
</head>
<body>
<form method="post"> 
	{% csrf_token %}
	{{form.as_p}}

	<button type="submit"> update </button>

</form>
</body>
</html>

Userapp/templates/feedback.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

 	 <style type="text/css">
 	 	body{
 	 		background-color: pink;
 	 	}
 	 </style>
</head>
<body>


<h3 align="center">Add your feedback..</h3> <hr>
<form method='post'>
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit"> Submit </button>
		
	</form>
</body>
</html>

Userapp/templates/full recipe.html
<h4> Recipes... </h4>


{% for recipe in recipelist %}
	Recipe name : {{ recipe.recipe_name }} <br>
	Recipe_pic : <img src="{{recipe.recipe_pic.url}}" width="10%"> <br>
	Ingrediants : {{recipe.ingrediants}} <br>
	Instructions : {{recipe.instructions|truncatechars:2}} <br>
	price : {{recipe.price}} <br>
{% endfor %}

Userapp/templates/fullrecipe.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <style type="text/css"> 
  		body{
  			background-color: pink;
  		}
  </style>

</head>
<body>

	<h3 align="center"> Recipes...</h3> <hr>

	{% for recipe in recipelist %}
	Recipe name : {{ recipe.recipe_name }} <br>
	Recipe_pic : <img src="{{recipe.recipe_pic.url}}" width="10%"> <br>
	Ingrediants : {{recipe.ingrediants}} <br>
	Instructions : {{recipe.instructions|truncatechars:2}} <br>
  Price : {{recipe.price}} <br>

	  <a href="{% url 'download' %}"> <button> download  </button> </a> 

	<hr>
{% endfor %}


</body>
</html>

Userapp/templates/home.html
<!DOCTYPE html>
<html>
<head>
{%load static%}
	<title> home page</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



	<style type="text/css">


	
	
	
		.class1{
			display: inline;
			padding-top:10px;
		}
		.navbar{
			padding-top: 35px;


		}
		.glyphicon{
			padding-bottom: 40px;


		}
		
		
		.class3{
			color:white;
		}

		#id1,#id2{
			font-family: "Lucida Console";
			font-weight: bold; 
		}
	</style>


</head>
<body>
	
	
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
	    		<div class="navbar-header">
					<a class="navbar-brand" href="#">AllRecipe</a>
				</div>
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'fullrecipe' %}">Home</a></li>
			

					<li> 
					 	<form method="post" action="{% url 'searchrecipe' %}">
							{%csrf_token%}
		                	 <input class="class1" type="text" placeholder="search recipe" name="search"> 
		     			 	<button class="class1" type="submit"> Go <i class="fa fa-search"></i></button> 
						</form>
					</li>
					
						

				</ul>

	    


	

				<ul class="nav navbar-nav navbar-right" class="class2">
	      


					{% if user.is_authenticated %}

					<a href="{% url 'userpage' %}"> <span class="glyphicon glyphicon-user"></span> Userpage </a>&nbsp;

					



					<a href="{% url 'logout' %}"> logout </a> 


					{%else%}

					<p class="class3"> you are not logged in </p>
					

						<a href="{% url 'login' %}" class="class3"> <span class="glyphicon glyphicon-user"></span> 
						 login </a> &nbsp;
						<a href="{% url 'register' %}" class="class3"> <span class="glyphicon glyphicon-log-in"></span> sign up </a>
					
					{% endif %}

				</ul>
			</div>
	
		</nav>
		<br>
		<div>


			<p id="id1"> Learn how to make desserts, snacks for the kids, dinner recipes, lunch ideas, breakfast recipes, quick and easy meals, slow cooker recipes, holiday meal ideas and so much more.</p> <br>
					<p id="id2">
					 Plan your weeknight dinners and find yummy weekend brunch recipes with the help of AllRecipe. Make meals using seasonal ingredients year-round with Allrecipe's spring, summer, fall and winter recipe ideas. Anyone who loves to cook and find new recipe ideas would enjoy this..Sign up now and join with us.. !<br> <br>
					</p>

		</div>
















<div class="container">
    
  	<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    	<ol class="carousel-indicators">
      		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
     		 <li data-target="#myCarousel" data-slide-to="1"></li>
     		 <li data-target="#myCarousel" data-slide-to="2"></li>
   		 </ol>

    <!-- Wrapper for slides -->
   		 <div class="carousel-inner">
     		<div class="item active">
       			 <img src="{% static '/images/image11.gif' %}" alt="" style="width:100%;">
     		</div>

      		<div class="item">
       			 <img src="{% static '/images/home1.gif' %}" alt="" style="width:100%;">
     		</div>
    
     		 <div class="item">
       			 <img src="{% static '/images/image11.gif' %}" alt="New york" style="width:100%;">
     		 </div>
    		</div>

    <!-- Left and right controls -->
    	<a class="left carousel-control" href="#myCarousel" data-slide="prev">
      		<span class="glyphicon glyphicon-chevron-left"></span>
      		<span class="sr-only">Previous</span>
   		 </a>
   		 <a class="right carousel-control" href="#myCarousel" data-slide="next">
     		 <span class="glyphicon glyphicon-chevron-right"></span>
     		 <span class="sr-only">Next</span>
    	</a>
  	</div>
</div>
















</body>

</html>
      			

Userapp/templates/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

Userapp/templates/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

Userapp/templates/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

Userapp/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <style type="text/css"> 
  		body{
  			background-color: pink;
  		}
  		#id1{
  			font-weight: bold;
  		}
  </style>

</head>
<body>
<br> <br> <br>
	<form method='post'>
		{% csrf_token %}
		{{form.as_p}} <br> <br>
		<button type="submit" id="id1"> Register </button>
		
	</form>

	
		

</body>
</html>

Userapp/templates/viewfeedback.html
<!DOCTYPE html>
<html>
<head>
	<title> </title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<style type="text/css">
		body{
			background-color: pink;
		}
	</style>
</head>
<body>
	<h3 align="center"> Feedbacks...! </h3> <hr>
	{% for i in feedback %}
		
		username : {{i.user_data.username}} <br>
		email : {{i.user_data.email}} <br>
		how you rate the website overall : {{i.how_you_rate_the_website_overall}} <br>
		suggestions : {{i.suggestions}}<br>

		<hr>
	{% endfor %}
</body>
</html>

Userapp/templates/viewrecipeus.html
<!DOCTYPE html>
<html>
<head>
	<title></title>

	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<style type="text/css">
body{
	background-color: pink;
}
</style>
</head>
<body>

	<h3> list of recipes </h3>
	{% for i in recipe %}
		<hr>

		Recipe name:{{i.recipe_name}} <br>
		Recipe picture: <img src="{{i.recipe_pic.url}}" width="10%"> <br>
 		Ingrediants : {{i.ingrediants}} <br>
 		Instructions : {{i.instructions|truncatechars:28}} <br>
 		price : {{i.price}} <br>

 		
 		

 		

 		<a href="{% url 'editrecipe' id=i.id %}"> edit recipe </a> &nbsp;

		<hr>
 {% endfor %}

</body>
</html>